version: 0.2

phases:
  build:
    commands:
      - echo Generating html...
      - cd docs
      - find . -name "*.adoc" -type f | xargs asciidoctor -r asciidoctor-diagram -D output
#      - rsync -vr --exclude='_*' --exclude='output' . output
      - cp -r images favicon.ico output
  post_build:
    commands:
      # ビルドフェーズで失敗したらアップロードを実行しない
      - if [[ "$CODEBUILD_BUILD_SUCCEEDING" == "0" ]]; then exit 1; else exit 0; fi
      - echo Uploading to S3...
      - aws s3 sync output s3://railroad-editor-doc/
