version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - apt-get install asciidoctor
  build:
    commands:
      - echo Generating html...
      - find . -name "*.adoc" -type f | xargs asciidoctor -r asciidoctor-diagram -D output
  post_build:
    commands:
      - (if [[ "$CODEBUILD_BUILD_SUCCEEDING" == "0" ]]; then exit 1; else exit 0; fi) ## ビルドフェーズで失敗したらアップロードを実行しない
      - echo Uploading to S3...
      - aws s3 sync output s3://$DESTINATION_BUCKET/